services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=petmatch'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=bel9sh'
    ports:
      - '6543:5432'
  minio:
    image: 'minio/minio'
    ports:
      - '9090:9000'
      - '9001:9001'
    environment:
      - 'MINIO_ROOT_USER=petmatch-access-key'
      - 'MINIO_ROOT_PASSWORD=petmatch-secret-key'
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
