services:
  postgres:
    image: "postgres:18"
    environment:
      - "POSTGRES_DB=petmatch"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_USER=bel9sh"
      - "SMTP_USERNAME=justanewacc9@gmail.com"
      - "SMTP_PASSWORD=mailpassword"
      - "SMTP_HOST=smtp.gmail.com"
      - "SMTP_PORT=587"
    ports:
      - "6543:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"