services:
  # PetMatch Postgres database
  petmatch-postgres:
    image: postgres:17-alpine
    container_name: petmatch-postgres
    restart: always
    ports:
      # Порт снаружи 5433, внутри контейнера 5432
      - "5433:5432"
    environment:
      POSTGRES_DB: petmatch
      POSTGRES_USER: petmatch
      POSTGRES_PASSWORD: secret
    volumes:
      # Прокидывание скрипта инициализации базы данных
      # ro суффикс = read-only файл
      - ./infrastructure/databases/petmatch:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U petmatch -p 5432" ]
      # Скрипт pg_isready будет запускаться с интервалом 10с, таймаут на выполнение скрипта 5с, макс. количество попыток 20
      interval: 10s
      timeout: 5s
      retries: 20
  # PetMatch Postgres database metrics exporter
  petmatch-postgres-metrics-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.0
    container_name: petmatch-postgres-metrics-exporter
    restart: always
    ports:
      - "9188:9187"
    # Экспортер метрик должен запускаться только после успешного запуска самой базы данных
    depends_on:
      petmatch-postgres:
        condition: service_healthy
    environment:
      # Шаблон: postgresql://username:password@hostname:port/database_name?sslmode=disable
      DATA_SOURCE_NAME: postgresql://petmatch:secret@petmatch-postgres:5432/petmatch?sslmode=disable
  # Prometheus metrics
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 10
  # Loki logs
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./infrastructure/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 10
  # Tempo tracings
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    restart: always
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    ports:
      - "3200:3200"
    volumes:
      - ./infrastructure/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/var/tempo
  # Alloy agent
  alloy:
    image: grafana/alloy:v1.10.2
    container_name: alloy
    restart: always
    ports:
      - "9080:9080" # HTTP Interface
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./infrastructure/alloy/config.alloy:/etc/alloy/config.alloy:ro
      # Помимо конфигурации, агенту Alloy необходим доступ до информации о контейнерах Docker, чтобы агент смог собирать данные с них
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
    environment:
      GRAFANA_LOKI_URL: http://loki:3100/loki/api/v1/push
    command:
      - run
      # Открываем доступ до Alloy UI по HTTP
      - --server.http.listen-addr=0.0.0.0:9080
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
  # Grafana UI
  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_started
      alloy:
        condition: service_started
    environment:
      # GF_AUTH_ANONYMOUS_ENABLED = true позволяет получить доступ до части функциональности без авторизации в Grafana
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_METRICS_ENABLED: "true"
    volumes:
      # Указание источников данных для Grafana при старте контейнера
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      # Подключение описаний dashboards в виде JSON напрямую в Grafana при старте контейнера
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
      - nexus-data:/nexus-data
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
  # PetMatch backend
  petmatch-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petmatch-service
    restart: always
    ports:
      - "8091:8091"
    environment:
      POSTGRES_HOST: petmatch-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: petmatch
      POSTGRES_USER: petmatch
      POSTGRES_PASSWORD: secret
      JWT_SECRET_ACCESS: f0210f36555fdbe73b701458876f657b14b09870b5fb2608ea21a6f4ef44e004
      JWT_SECRET_REFRESH: ToSDlXMK0jFRrllnZEJ9qEw7gT0K5mdyKdCF3gvOMK4=
      OTLP_EXPORTER_ENDPOINT: http://tempo:4318
      JAVA_OPTS: "-XX:+UseG1GC -XX:+UseContainerSupport"
      REDIS_HOST: petmatch-redis
      REDIS_PASSWORD: secret
      REDIS_DEFAULT_VERIFICATION_CODE_TTL: 30
      REDIS_DEFAULT_TTL: 30
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: localhost@user.com
      SPRING_MAIL_PASSWORD: ""
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
      MINIO_ENDPOINT: http://petmatch-minio:9000
      MINIO_ACCESS_KEY: miniosecret
      MINIO_SECRET_KEY: miniosecret
      MINIO_BUCKET_NAME: petmatch-uploads
    depends_on:
      petmatch-postgres:
        condition: service_healthy
      petmatch-minio:
        condition: service_healthy
      petmatch-redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-i", "http://localhost:8091/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 3
  # Redis cache
  petmatch-redis:
    image: redis:7-alpine
    container_name: petmatch-redis
    restart: always
    command: redis-server --appendonly yes --requirepass secret --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
  # Redis metrics exporter
  redis-exporter:
    image: oliver006/redis_exporter:v1.70.0
    container_name: redis-exporter
    restart: always
    ports:
      - "9121:9121"
    depends_on:
      petmatch-redis:
        condition: service_healthy
    environment:
      REDIS_ADDR: "redis://petmatch-redis:6379"
      REDIS_PASSWORD: secret
    command:
      - '--redis.addr=redis://petmatch-redis:6379'
      - '--redis.password=secret'
  # MinIO object storage (S3)
  petmatch-minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: petmatch-minio
    restart: always
    ports:
      - "9001:9001"
      - "9000:9000"
    command: server /data --console-address ":9001" --address ":9000"
    environment:
      # То же самое, что access key
      MINIO_ROOT_USER: admin
      # То же самое, что secret key
      MINIO_ROOT_PASSWORD: miniosecret
      MINIO_DEFAULT_BUCKETS: petmatch-uploads
      MINIO_PROMETHEUS_AUTH_TYPE: "public" # Make metrics publicly accessible
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

# Docker volumes to save services data
volumes:
  artifacts:
  tempo_data:
  nexus-data:
  loki_data:
  loki_chunks:
  loki_index:
  loki_rules:
  postgres_data:
  redis_data:
  minio_data:
