server:
  port: 8091

app:
  timezone: "Europe/Moscow"

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/petmatch
    username: petmatch
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: secret
      verification-code:
        ttl-minutes: 5
      default-ttl-minutes: 60
  mail:
    host: localhost
    port: 1025
    username: "example@user.com"
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
minio:
  endpoint: http://localhost:9000
  access-key: petmatch-access-key
  secret-key: petmatch-secret-key
  bucket-name: petmatch-uploads
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none
