package org.nsu.authorization.core.utils;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.nsu.authorization.core.services.VerificationCodeCachingService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.cache.concurrent.ConcurrentMapCacheManager;
import org.springframework.context.annotation.Bean;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest(classes = {
        org.nsu.authorization.core.services.VerificationCodeCachingService.class,
        VerificationCodeGenerator.class,
        VerificationCodeGeneratorIntegrationTest.TestCachingConfig.class
})
@EnableCaching
class VerificationCodeGeneratorIntegrationTest {

    @Autowired
    private VerificationCodeCachingService verificationCodeCachingService;

    @Autowired
    private CacheManager cacheManager;

    private static final String CACHE_NAME = "Verification codes";
    // The key must match the one used in RegistrationService:
    // "registrationService:user:1:email:code"
    private static final String TEST_KEY_USER_IDX = "1";

    @AfterEach
    void tearDown() {
        cacheManager.getCache(CACHE_NAME).clear();
    }

    @Test
    void testGenerateVerificationCodeAndCacheIt() {
        assertNotNull(cacheManager, "CacheManager should be injected successfully.");

        // 1. Generate the code (This uses @CachePut, so it executes and saves the
        // result)
        String code1 = verificationCodeCachingService.generateAndCacheCode(TEST_KEY_USER_IDX);

        // 2. Retrieve the code using the *Cacheable* method (getCode)
        // This confirms the value stored by @CachePut is readable.
        String cachedCode = verificationCodeCachingService.getCode(TEST_KEY_USER_IDX);

        // 3. (Optional) Call generateAndCacheCode a second time. This should return a
        // *new* code
        // because it uses @CachePut, which we expect to overwrite the cache.
        String code2 = verificationCodeCachingService.generateAndCacheCode(TEST_KEY_USER_IDX);

        assertNotNull(code1, "The generated code should not be null.");

        // ASSERTION 1: Check if the cache contains the first generated code
        assertEquals(code1, cachedCode,
                "The code retrieved using getCode should match the one generated by generateAndCacheCode.");

        // ASSERTION 2: Check if the *second* generation call produced a *new* code
        // (required if using @CachePut)
        assertNotEquals(code1, code2, "The second call to the @CachePut method should generate a new, different code.");
    }

    /**
     * Test Configuration to provide a simple in-memory CacheManager,
     * satisfying the @Cacheable dependency without requiring a live Redis
     * connection.
     */
    @TestConfiguration
    @EnableCaching
    static class TestCachingConfig {
        @Bean
        public CacheManager cacheManager() {
            // Must define the cache name used in the service: "Verification codes"
            // The ConcurrentMapCacheManager creates a simple, in-memory cache.
            return new ConcurrentMapCacheManager(CacheUtil.VERIFICATION_CODE_CACHE_NAME);
        }
    }
}