name: Backend CI/CD

on:
  pull_request:
    branches: [ '*', 'develop', 'master' ]
  push:
    branches: [ 'develop', 'master' ]

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run tests
        run: ./mvnw test